### ISSUE TITLE
missing display functions

### ISSUE THREAD

**Issue by smmoosavi** [alitaheri/material-ui-pickers-jalali-utils#1]
material-ui-pickers v1.0.0-rc.2 need few new functions which is missing in material-ui-pickers-jalali-utils and cause error:
https://github.com/dmtrKovalenko/material-ui-pickers/blob/da00ff9c44a49982706d7d5af570a42f946ce3c5/lib/src/utils/moment-utils.js#L152-L179

**Comment by alitaheri** [comment]
@smmoosavi This was a test release. I'll get it fixed. [reference](https://github.com/dmtrKovalenko/material-ui-pickers/pull/241)

I suggest you fall back to version 2.

**Comment by smmoosavi** [comment]
txn

**Comment by alitaheri** [comment]
This is fixed now
