### ISSUE TITLE
problem with keyboard attr

### ISSUE THREAD

**Issue by themojilla** [alitaheri/material-ui-pickers-jalali-utils#4]
A bunch of thanks for this repo,
The problem is if I set the "keyboard" option for material-ui-pickers to let user input date,
It won't work due to user's inputs
Any idea?

**Comment by alitaheri** [comment]
`moment-jalaali` has a quirk where it successfully parses an invalid (half) typed-in date string but returns wrong results. since it's not invalid it gets set on the date picker component rendering keyboard input completely useless. I had to hack around it in my own code. but I still haven't figured out a proper way to handle this usecase. I'll share my hack with you here. But don't expect it to work all the time 😅 

```js
import jMoment from 'moment-jalaali';

jMoment.loadPersian({ dialect: 'persian-modern' });

const originalParse = JalaliUtils.prototype.parse;
const originalFormat = JalaliUtils.prototype.format;

// Hack around a bug causing weird behavior when using keyboard input
JalaliUtils.prototype.parse = (value, format) => {
  if (value.includes('_')) {
    return jMoment.invalid();
  }

  let date = originalParse(value, format);

  return jMoment({
    year: date.year() === 0 ? new Date().getFullYear() : date.year(),
    month: date.year() === 0 ? new Date().getMonth() : date.month(),
    date: date.year() === 0 ? new Date().getDate() : date.date(),
    hour: date.hour() + (value.includes(ب.ظ") ? 12 : 0"),
    minute: date.minute(),
    second: date.second(),
    millisecond: date.millisecond(),
  });
}

JalaliUtils.prototype.format = (date, format) => {
  if (!date.isValid()) {
    return '';
  }

  return originalFormat(date, format);
}
```

Put this code snippet before any usage of the library. Hope this helps. give me feedback when you test it out. Thanks 👍

**Comment by themojilla** [comment]
I'll inform you
Thank you @alitaheri

**Comment by inamvar** [comment]
@alitaheri  I used this hack and got this error :

![image](https://user-images.githubusercontent.com/6972027/113104396-bdba3e00-9215-11eb-8f9f-e1b7c1dc353d.png)

**Comment by alitaheri** [comment]
@inamvar  Did it happen after this change? does it work without this? because @date-io has compatibility issues on it's own. if you're not sure if this is the actual cause please provide your @date-io and @material-ui/pickers versions

**Comment by inamvar** [comment]
@alitaheri yes. Its working properly without that,  here is versions:
- `@date-io/jalaali@1.3.13`
- `@material-ui/pickers": "^3.2.10"`

**Comment by alitaheri** [comment]
Yeah, it's not version incompatibility. This isn't enough for me to debug. You'll have to find the problem on your own. but please be kind and share once you  solve it. I'm sure others will end up with the same issue eventually. It's weird why undefined is passed to that function. none of the methods above return undefined.
